# dbt Project Configuration for MSSQL to Redshift Migration
# Amazon Q Developer automated conversion setup

name: 'mssql_migration'
version: '1.0.0'
config-version: 2

# Redshift-specific profile
profile: 'redshift_warehouse'

# Model paths
model-paths: ["dbt_models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Redshift-optimized configurations
models:
  mssql_migration:
    +materialized: table
    +sort: ['created_at']
    +dist: 'even'
    
    # Regional security models
    sales:
      +materialized: view
      +tags: ['security', 'regional']
    
    analytics:
      +materialized: table
      +sort: ['total_revenue']
      +tags: ['analytics']

# Variables for regional security
vars:
  # Default values - override in profiles.yml or CLI
  start_date: '2024-01-01'
  end_date: '2024-12-31'
  user_region: 'NORTH'
  report_month: 1
  report_year: 2024

# Redshift-specific configurations
on-run-start:
  - "{{ log('Starting dbt run for Redshift warehouse', info=true) }}"

on-run-end:
  - "{{ log('Completed dbt run', info=true) }}"